<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Enums\ChampionshipMatchStatus as ChampionshipMatchStatusEnum;
use App\Enums\ChampionshipRoundType as ChampionshipRoundTypeEnum;
use App\Enums\ChampionshipResultType as ChampionshipResultTypeEnum;
use App\Services\ChampionshipMatchPlayerService;

class ChampionshipMatchRefactored extends Model
{
    use HasFactory;

    protected $table = 'championship_matches';

    protected $fillable = [
        'championship_id',
        'round_number',
        'round_type',       // Virtual attribute (mutator converts to round_type_id)
        'round_type_id',    // FK to championship_round_types table
        'white_player_id',  // Player assigned white pieces (PRIMARY)
        'black_player_id',  // Player assigned black pieces (PRIMARY)
        'color_assignment_method', // Method used: balanced, alternate, random
        'auto_generated',   // Auto-generated by system
        // Placeholder match support
        'is_placeholder',   // Match with TBD players based on rankings
        'placeholder_positions', // JSON: rank positions (e.g., {"player1": "rank_1", "player2": "rank_2"})
        'players_assigned_at', // When actual players were assigned to placeholder
        'determined_by_round', // Which round's results determine this match's players
        'game_id',
        'scheduled_at',
        'deadline',
        'invitation_sent_at',
        'invitation_accepted_at',
        'invitation_status', // pending, accepted, declined, expired
        'winner_id',
        'result_type',      // Virtual attribute (mutator converts to result_type_id)
        'result_type_id',   // FK to championship_result_types table
        'status',           // Virtual attribute (mutator converts to status_id)
        'status_id',        // FK to championship_match_statuses table
        // Scheduling fields
        'scheduled_time',
        'game_timeout',
        'scheduling_status',
        'can_schedule_early',
        'scheduling_notes',
        // Legacy fields (deprecated - kept for backward compatibility)
        'player1_id',
        'player2_id',
    ];

    protected $casts = [
        'championship_id' => 'integer',
        'round_number' => 'integer',
        'round_type_id' => 'integer',
        'white_player_id' => 'integer',
        'black_player_id' => 'integer',
        'color_assignment_method' => 'string',
        'auto_generated' => 'boolean',
        // Placeholder match casts
        'is_placeholder' => 'boolean',
        'placeholder_positions' => 'array',
        'players_assigned_at' => 'datetime',
        'determined_by_round' => 'integer',
        'game_id' => 'integer',
        'scheduled_at' => 'datetime',
        'deadline' => 'datetime',
        'invitation_sent_at' => 'datetime',
        'invitation_accepted_at' => 'datetime',
        'invitation_status' => 'string',
        'winner_id' => 'integer',
        'result_type_id' => 'integer',
        'status_id' => 'integer',
        // Scheduling field casts
        'scheduled_time' => 'datetime',
        'game_timeout' => 'datetime',
        'can_schedule_early' => 'boolean',
        // Legacy fields (deprecated)
        'player1_id' => 'integer',
        'player2_id' => 'integer',
    ];

    /**
     * Append accessor attributes to JSON serialization
     */
    protected $appends = [
        'status',
        'round_type',
        'result_type',
    ];

    // Relationships

    /**
     * The championship this match belongs to
     */
    public function championship()
    {
        return $this->belongsTo(Championship::class);
    }

    /**
     * White player (PRIMARY)
     */
    public function whitePlayer()
    {
        return $this->belongsTo(User::class, 'white_player_id');
    }

    /**
     * Black player (PRIMARY)
     */
    public function blackPlayer()
    {
        return $this->belongsTo(User::class, 'black_player_id');
    }

    /**
     * The game associated with this match
     */
    public function game()
    {
        return $this->belongsTo(Game::class);
    }

    /**
     * The winner of match
     */
    public function winner()
    {
        return $this->belongsTo(User::class, 'winner_id');
    }

    /**
     * Relationship to ChampionshipMatchStatus lookup table
     */
    public function statusRelation()
    {
        return $this->belongsTo(ChampionshipMatchStatus::class, 'status_id');
    }

    /**
     * Relationship to ChampionshipRoundType lookup table
     */
    public function roundTypeRelation()
    {
        return $this->belongsTo(ChampionshipRoundType::class, 'round_type_id');
    }

    /**
     * Alias for roundTypeRelation for consistency
     */
    public function roundType()
    {
        return $this->roundTypeRelation();
    }

    /**
     * Relationship to ChampionshipResultType lookup table
     */
    public function resultTypeRelation()
    {
        return $this->belongsTo(ChampionshipResultType::class, 'result_type_id');
    }

    /**
     * Alias for resultTypeRelation for consistency
     */
    public function resultType()
    {
        return $this->resultTypeRelation();
    }

    /**
     * Get the scheduling proposals for this match
     */
    public function schedules()
    {
        return $this->hasMany(ChampionshipMatchSchedule::class, 'championship_match_id');
    }

    /**
     * Get the current active schedule proposal
     */
    public function currentSchedule()
    {
        return $this->schedules()
            ->whereIn('status', ['proposed', 'accepted', 'alternative_proposed'])
            ->latest()
            ->first();
    }

    // Legacy Relationships (deprecated - use whitePlayer/blackPlayer instead)

    /**
     * Player 1 (DEPRECATED - use whitePlayer instead)
     */
    public function player1()
    {
        return $this->belongsTo(User::class, 'player1_id');
    }

    /**
     * Player 2 (DEPRECATED - use blackPlayer instead)
     */
    public function player2()
    {
        return $this->belongsTo(User::class, 'player2_id');
    }

    // Mutators & Accessors

    /**
     * Mutator: Convert status string/enum to status_id FK
     */
    public function setStatusAttribute($value)
    {
        if ($value instanceof ChampionshipMatchStatusEnum) {
            $code = $value->value;
        } else {
            $code = $value;
        }

        $this->attributes['status_id'] = ChampionshipMatchStatus::getIdByCode($code);
    }

    /**
     * Accessor: Read status code from relationship
     */
    public function getStatusAttribute(): string
    {
        if (isset($this->attributes['status_id'])) {
            return $this->statusRelation?->code ??
                   ChampionshipMatchStatus::find($this->attributes['status_id'])?->code ??
                   'pending';
        }

        return 'pending';
    }

    /**
     * Mutator: Convert round type string/enum to round_type_id FK
     */
    public function setRoundTypeAttribute($value)
    {
        if ($value instanceof ChampionshipRoundTypeEnum) {
            $code = $value->value;
        } else {
            $code = $value;
        }

        $this->attributes['round_type_id'] = ChampionshipRoundType::getIdByCode($code);
    }

    /**
     * Accessor: Read round type code from relationship
     */
    public function getRoundTypeAttribute(): string
    {
        if (isset($this->attributes['round_type_id'])) {
            return $this->roundTypeRelation?->code ??
                   ChampionshipRoundType::find($this->attributes['round_type_id'])?->code ??
                   'swiss';
        }

        return 'swiss';
    }

    /**
     * Mutator: Convert result type string/enum to result_type_id FK
     */
    public function setResultTypeAttribute($value)
    {
        if ($value === null) {
            $this->attributes['result_type_id'] = null;
            return;
        }

        if ($value instanceof ChampionshipResultTypeEnum) {
            $code = $value->value;
        } else {
            $code = $value;
        }

        $this->attributes['result_type_id'] = ChampionshipResultType::getIdByCode($code);
    }

    /**
     * Accessor: Read result type code from relationship
     */
    public function getResultTypeAttribute(): ?string
    {
        if (isset($this->attributes['result_type_id']) && $this->attributes['result_type_id'] !== null) {
            return $this->resultTypeRelation?->code ??
                   ChampionshipResultType::find($this->attributes['result_type_id'])?->code;
        }

        return null;
    }

    // Scopes

    /**
     * Scope: Pending matches
     */
    public function scopePending($query)
    {
        return $query->where('status_id', ChampionshipMatchStatusEnum::PENDING->getId());
    }

    /**
     * Scope: In progress matches
     */
    public function scopeInProgress($query)
    {
        return $query->where('status_id', ChampionshipMatchStatusEnum::IN_PROGRESS->getId());
    }

    /**
     * Scope: Completed matches
     */
    public function scopeCompleted($query)
    {
        return $query->where('status_id', ChampionshipMatchStatusEnum::COMPLETED->getId());
    }

    /**
     * Scope: Not completed matches (pending, in_progress, scheduled, etc.)
     */
    public function scopeWhereNotCompleted($query)
    {
        return $query->where('status_id', '!=', ChampionshipMatchStatusEnum::COMPLETED->getId());
    }

    /**
     * Scope: Matches for a specific round
     */
    public function scopeForRound($query, ?int $roundNumber)
    {
        if ($roundNumber === null) {
            return $query;
        }
        return $query->where('round_number', $roundNumber);
    }

    /**
     * Scope: Expired matches
     */
    public function scopeExpired($query)
    {
        return $query->where('deadline', '<', now())
                    ->where('status_id', '!=', ChampionshipMatchStatusEnum::COMPLETED->getId());
    }

    /**
     * Scope: Matches where user is a player (uses service for consistent logic)
     */
    public function scopeWherePlayer($query, int $userId)
    {
        return ChampionshipMatchPlayerService::wherePlayer($query, $userId);
    }

    // Helper Methods (using service class)

    /**
     * Get white player ID (single source of truth)
     */
    public function getWhitePlayerId(): ?int
    {
        return ChampionshipMatchPlayerService::getWhitePlayerId($this);
    }

    /**
     * Get black player ID (single source of truth)
     */
    public function getBlackPlayerId(): ?int
    {
        return ChampionshipMatchPlayerService::getBlackPlayerId($this);
    }

    /**
     * Get all player IDs from this match
     */
    public function getAllPlayerIds(): array
    {
        return ChampionshipMatchPlayerService::getAllPlayerIds($this);
    }

    /**
     * Check if user is a player in this match
     */
    public function hasPlayer(int $userId): bool
    {
        return ChampionshipMatchPlayerService::isPlayerInMatch($this, $userId);
    }

    /**
     * Get opponent for a given player
     */
    public function getOpponent(int $userId): ?User
    {
        return ChampionshipMatchPlayerService::getOpponent($this, $userId);
    }

    /**
     * Get player's color in this match
     */
    public function getPlayerColor(int $userId): ?string
    {
        return ChampionshipMatchPlayerService::getPlayerColor($this, $userId);
    }

    /**
     * Assign players to match with colors (updates all fields for consistency)
     */
    public function assignPlayers(int $whitePlayerId, int $blackPlayerId): void
    {
        ChampionshipMatchPlayerService::assignPlayers($this, $whitePlayerId, $blackPlayerId);
    }

    /**
     * Check if match has both players assigned with colors
     */
    public function hasCompleteColorAssignment(): bool
    {
        return ChampionshipMatchPlayerService::hasCompletePlayers($this);
    }

    /**
     * Get status as enum
     */
    public function getStatusEnum(): ChampionshipMatchStatusEnum
    {
        return ChampionshipMatchStatusEnum::from($this->status);
    }

    /**
     * Get round type as enum
     */
    public function getRoundTypeEnum(): ChampionshipRoundTypeEnum
    {
        return ChampionshipRoundTypeEnum::from($this->round_type);
    }

    /**
     * Get result type as enum (nullable)
     */
    public function getResultTypeEnum(): ?ChampionshipResultTypeEnum
    {
        return $this->result_type ? ChampionshipResultTypeEnum::from($this->result_type) : null;
    }

    /**
     * Mark match as completed
     */
    public function markAsCompleted(int $winnerId, string $resultType): void
    {
        $this->update([
            'winner_id' => $winnerId,
            'result_type' => $resultType,
            'status' => ChampionshipMatchStatusEnum::COMPLETED->value,
        ]);
    }

    /**
     * Handle forfeit by white player
     */
    public function forfeitWhitePlayer(): void
    {
        $blackPlayerId = $this->getBlackPlayerId();
        if ($blackPlayerId) {
            $this->markAsCompleted(
                $blackPlayerId,
                ChampionshipResultTypeEnum::FORFEIT_PLAYER1->value
            );
        }
    }

    /**
     * Handle forfeit by black player
     */
    public function forfeitBlackPlayer(): void
    {
        $whitePlayerId = $this->getWhitePlayerId();
        if ($whitePlayerId) {
            $this->markAsCompleted(
                $whitePlayerId,
                ChampionshipResultTypeEnum::FORFEIT_PLAYER2->value
            );
        }
    }

    /**
     * Handle double forfeit
     */
    public function doubleForfeit(): void
    {
        $this->update([
            'winner_id' => null,
            'result_type' => ChampionshipResultTypeEnum::DOUBLE_FORFEIT->value,
            'status' => ChampionshipMatchStatusEnum::COMPLETED->value,
        ]);
    }

    /**
     * Check if match has expired
     */
    public function hasExpired(): bool
    {
        return now()->greaterThan($this->deadline) &&
               !$this->getStatusEnum()->isFinished();
    }

    /**
     * Check if a player can play in this match based on round progression
     *
     * @param int $userId
     * @return array ['canPlay' => bool, 'reason' => string|null]
     */
    public function canPlayerPlay(int $userId): array
    {
        // Players can always play round 1
        if ($this->round_number === 1) {
            return ['canPlay' => true, 'reason' => null];
        }

        // Check if this player is actually in this match
        if (!$this->hasPlayer($userId)) {
            return ['canPlay' => false, 'reason' => 'You are not a participant in this match'];
        }

        // Check if player has completed their previous round match
        $previousRoundMatch = self::where('championship_id', $this->championship_id)
            ->where('round_number', $this->round_number - 1)
            ->wherePlayer($userId)
            ->first();

        if (!$previousRoundMatch) {
            return ['canPlay' => false, 'reason' => 'Previous round match not found'];
        }

        // Use status_id for reliable comparison
        if ($previousRoundMatch->status_id !== ChampionshipMatchStatusEnum::COMPLETED->getId()) {
            return ['canPlay' => false, 'reason' => 'You must complete your Round ' . ($this->round_number - 1) . ' match first'];
        }

        // Check if player qualified (didn't get eliminated)
        if ($previousRoundMatch->winner_id && $previousRoundMatch->winner_id !== $userId) {
            $championship = $this->championship;
            // For knockout tournaments, losing means elimination
            if ($championship && $championship->format === 'single_elimination') {
                return ['canPlay' => false, 'reason' => 'You were eliminated in Round ' . ($this->round_number - 1)];
            }
        }

        return ['canPlay' => true, 'reason' => null];
    }

    // Invitation Methods

    /**
     * Mark invitation as sent
     */
    public function markInvitationSent(): void
    {
        $this->update([
            'invitation_sent_at' => now(),
            'invitation_status' => 'pending'
        ]);
    }

    /**
     * Mark invitation as accepted
     */
    public function markInvitationAccepted(): void
    {
        $this->update([
            'invitation_accepted_at' => now(),
            'invitation_status' => 'accepted',
            'status' => 'scheduled'
        ]);
    }

    /**
     * Mark invitation as declined
     */
    public function markInvitationDeclined(): void
    {
        $this->update([
            'invitation_status' => 'declined',
            'status' => 'pending'
        ]);
    }

    /**
     * Check if invitation is pending
     */
    public function isInvitationPending(): bool
    {
        return $this->invitation_status === 'pending';
    }

    /**
     * Check if invitation was accepted
     */
    public function isInvitationAccepted(): bool
    {
        return $this->invitation_status === 'accepted';
    }

    /**
     * Get match duration in minutes
     */
    public function getDurationMinutes(): ?int
    {
        if (!$this->scheduled_at || !$this->completed_at) {
            return null;
        }

        return $this->scheduled_at->diffInMinutes($this->completed_at);
    }

    // Placeholder Match Methods

    /**
     * Check if this is a placeholder match
     */
    public function isPlaceholder(): bool
    {
        return $this->is_placeholder === true;
    }

    /**
     * Check if placeholder has been assigned players
     */
    public function hasAssignedPlayers(): bool
    {
        return $this->isPlaceholder() &&
               !is_null($this->players_assigned_at) &&
               $this->hasCompleteColorAssignment();
    }

    /**
     * Get placeholder position for a player slot
     *
     * @param string $slot 'white' or 'black'
     * @return string|null e.g., 'rank_1', 'rank_2'
     */
    public function getPlaceholderPosition(string $slot): ?string
    {
        if (!$this->isPlaceholder() || !$this->placeholder_positions) {
            return null;
        }

        $slotMap = [
            'white' => 'player1',
            'black' => 'player2',
        ];

        $legacySlot = $slotMap[$slot] ?? $slot;
        return $this->placeholder_positions[$legacySlot] ?? null;
    }

    /**
     * Assign players to placeholder match based on rankings
     *
     * @param int $whitePlayerId Player to assign as white
     * @param int $blackPlayerId Player to assign as black
     */
    public function assignPlaceholderPlayers(int $whitePlayerId, int $blackPlayerId): void
    {
        if (!$this->isPlaceholder()) {
            throw new \LogicException('Cannot assign players to non-placeholder match');
        }

        $this->assignPlayers($whitePlayerId, $blackPlayerId);

        $this->update([
            'players_assigned_at' => now(),
        ]);
    }

    /**
     * Get human-readable placeholder description
     */
    public function getPlaceholderDescription(): ?string
    {
        if (!$this->isPlaceholder() || !$this->placeholder_positions) {
            return null;
        }

        $whitePos = $this->placeholder_positions['player1'] ?? 'TBD';
        $blackPos = $this->placeholder_positions['player2'] ?? 'TBD';

        // Convert 'rank_1' to 'Rank #1'
        $whitePosDisplay = ucfirst(str_replace('_', ' #', $whitePos));
        $blackPosDisplay = ucfirst(str_replace('_', ' #', $blackPos));

        return "{$whitePosDisplay} (White) vs {$blackPosDisplay} (Black)";
    }

    /**
     * Validate match data consistency
     */
    public function validateConsistency(): array
    {
        return ChampionshipMatchPlayerService::validateConsistency($this);
    }
}