<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (Schema::hasTable('championship_matches') && !Schema::hasColumn('championship_matches', 'white_player_id')) {
            Schema::table('championship_matches', function (Blueprint $table) {
                // Add explicit color assignment fields
                $table->foreignId('white_player_id')->nullable()->after('player2_id')->comment('Player assigned white pieces');
                $table->foreignId('black_player_id')->nullable()->after('white_player_id')->comment('Player assigned black pieces');

                // Add tournament control fields
                $table->string('color_assignment_method', 20)->default('balanced')->after('black_player_id')->comment('Method used for color assignment: balanced, alternate, random');
                $table->boolean('auto_generated')->default(false)->after('color_assignment_method')->comment('Whether this match was auto-generated by the system');

                // Add invitation tracking fields
                $table->timestamp('invitation_sent_at')->nullable()->after('deadline')->comment('When match invitations were sent');
                $table->timestamp('invitation_accepted_at')->nullable()->after('invitation_sent_at')->comment('When match invitations were accepted');
                $table->string('invitation_status', 20)->default('pending')->after('invitation_accepted_at')->comment('Invitation status: pending, accepted, declined, expired');

                // Add foreign key constraints for color assignment
                $table->foreign('white_player_id')->references('id')->on('users')->onDelete('set null');
                $table->foreign('black_player_id')->references('id')->on('users')->onDelete('set null');

                // Add indexes for performance
                $table->index(['white_player_id']);
                $table->index(['black_player_id']);
                $table->index(['championship_id', 'round_number', 'invitation_status'], 'champ_match_invitation_idx');
            });

            // Migrate existing data: set player1 as white, player2 as black
            DB::statement('
                UPDATE championship_matches
                SET white_player_id = player1_id,
                    black_player_id = player2_id,
                    color_assignment_method = "balanced"
                WHERE white_player_id IS NULL
            ');
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (Schema::hasTable('championship_matches') && Schema::hasColumn('championship_matches', 'white_player_id')) {
            Schema::table('championship_matches', function (Blueprint $table) {
                $table->dropForeign(['white_player_id']);
                $table->dropForeign(['black_player_id']);
                $table->dropIndex(['white_player_id']);
                $table->dropIndex(['black_player_id']);
                $table->dropIndex('champ_match_invitation_idx');

                $table->dropColumn([
                    'white_player_id',
                    'black_player_id',
                    'color_assignment_method',
                    'auto_generated',
                    'invitation_sent_at',
                    'invitation_accepted_at',
                    'invitation_status'
                ]);
            });
        }
    }
};